# Generated by Django 6.0.1 on 2026-01-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZomatoDB',
            fields=[
                ('OrderNo', models.IntegerField(primary_key=True, serialize=False)),
                ('OrderName', models.CharField(max_length=10)),
                ('Bill', models.FloatField()),
                ('Mobile_no', models.IntegerField()),
                ('Address', models.CharField(max_length=40)),
                ('DeliveryName', models.CharField(max_length=10)),
            ],
        ),
    ]
